# https://developer.hashicorp.com/vagrant/docs/vagrantfile/machine_settings
Vagrant.configure("2") do |config|
  config.vm.guest = "openbsd"

  # By default, Vagrant will check for updates to the configured box on every vagrant up. If an update is found, Vagrant will tell the user. As this box is meant to be used ephemerally and asynchronously, these checks are unnecessary.
  config.vm.box_check_update = false

  # By default, Vagrant will share your project directory (the directory with the Vagrantfile) to /vagrant. Disable it, as it's unnecessary and probably unsupported for OpenBSD.
  # https://developer.hashicorp.com/vagrant/docs/synced-folders
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration
  config.vm.provider "virtualbox" do |virtualbox|
 
    # Ubuntu-Linux GitHub-hosted runners have 4 vCPUs and 16 GiB of RAM. Most of it should be reallocated to the guest.
    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    virtualbox.cpus = 4
    virtualbox.memory = 15 * 1024

    # By default Vagrant will check for the VirtualBox Guest Additions when starting a machine, and will output a warning if the guest additions are missing or out-of-date.
    virtualbox.check_guest_additions = false
  end

  # SSH configuration settings with which Vagrant will use for `vagrant ssh`.
  # https://developer.hashicorp.com/vagrant/docs/vagrantfile/ssh_settings
  config.ssh.username = "root"
  config.ssh.insert_key = false
  config.ssh.sudo_command = "doas %c"
  config.ssh.shell = "ksh -l"
  config.ssh.forward_env = [
    "CI",
    "GITHUB_ACTION",
    "GITHUB_ACTION_PATH",
    "GITHUB_ACTION_REPOSITORY",
    "GITHUB_ACTIONS",
    "GITHUB_ACTOR",
    "GITHUB_ACTOR_ID",
    "GITHUB_API_URL",
    "GITHUB_BASE_REF",
    "GITHUB_ENV",
    "GITHUB_EVENT_NAME",
    "GITHUB_EVENT_PATH",
    "GITHUB_GRAPHQL_URL",
    "GITHUB_HEAD_REF",
    "GITHUB_JOB",
    "GITHUB_OUTPUT",
    "GITHUB_PATH",
    "GITHUB_REF",
    "GITHUB_REF_NAME",
    "GITHUB_REF_PROTECTED",
    "GITHUB_REF_TYPE",
    "GITHUB_REPOSITORY",
    "GITHUB_REPOSITORY_ID",
    "GITHUB_REPOSITORY_OWNER",
    "GITHUB_REPOSITORY_OWNER_ID",
    "GITHUB_RETENTION_DAYS",
    "GITHUB_RUN_ATTEMPT",
    "GITHUB_RUN_ID",
    "GITHUB_RUN_NUMBER",
    "GITHUB_SERVER_URL",
    "GITHUB_SHA",
    "GITHUB_STEP_SUMMARY",
    "GITHUB_TRIGGERING_ACTOR",
    "GITHUB_WORKFLOW",
    "GITHUB_WORKFLOW_REF",
    "GITHUB_WORKFLOW_SHA",
    "GITHUB_WORKSPACE",
    "RUNNER_ARCH",
    "RUNNER_DEBUG",
    "RUNNER_ENVIRONMENT",
    "RUNNER_NAME",
    "RUNNER_OS",
    "RUNNER_TEMP",
    "RUNNER_TOOL_CACHE",
    "FOO",
  ]
end
